
server:
  port: 5555

spring:
  application:
    name: api-gateway  # Sets the name of this application (useful for Eureka and logging)

  main:
    web-application-type: reactive  # Required for Spring Cloud Gateway (uses WebFlux/reactive stack)

  cloud:
    gateway:
      routes:  # List of routes this API Gateway will handle

        # ----------- Route 1: Authentication Service -----------
        - id: auth-service-app  # Unique ID for this route
          uri: lb://AUTHSERVICEAPP  # Forward requests to AUTHSERVICEAPP service using load balancing (via Eureka)
          predicates:
            - Path=/api/auth/**  # Match any request with path starting with /api/auth/
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}  # Remove /api/auth prefix before forwarding

        # ----------- Route 2: Microservice 1 -----------
        - id: microservice-api-1  # Unique ID for this route
          uri: lb://MICROSERVICES1  # Forward requests to MICROSERVICES1 service using load balancing
          predicates:
            - Path=/micro1/**  # Match any request with path starting with /micro1/
          filters:
            - RewritePath=/micro1/(?<segment>.*), /${segment}  # Remove /micro1 prefix before forwarding
